name: 'Publish results'
description: 'Publish the results of a Gradle build'
runs:
  using: "composite"
  steps:

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Unit Test Results
        junit_files: |
          build/**/test-results/**/*.xml

    - name: Archive build results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ${{ github.event.repository.name }}-${{github.run_number}}-build
        path: build

    - name: Archive output
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: ${{ github.event.repository.name }}-${{github.run_number}}-artifacts
        path: build/artifacts
