name: Test no input
on:
  push:

permissions:
  checks: write
  pull-requests: write

jobs:
  test-no-input:
    runs-on: ubuntu-latest
    steps:
      - uses: Mahoney-github-actions/gradle-build-output@improve
