name: Test failure
on:
  push:

permissions:
  checks: write
  pull-requests: write

jobs:
  test-failure:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Failed!'; exit 1
      - uses: Mahoney-github-actions/gradle-build-output@improve
        if: always()
        with:
          is_success: ${{ success() }}
