name: Test failure
on:
  push:

permissions:
  checks: write
  pull-requests: write

jobs:
  test-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: Mahoney-github-actions/gradle-build-output@improve
        with:
          is_success: false

